name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install & Build
        run: |
          npm ci
          npm run build
        env:
          BASE_URL: /drotr/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages

  update-test-coverage-badge:
    needs: deploy-to-gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy coverage report to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage
          branch: gh-pages
          target-folder: coverage
          clean: false
